theme = 'carbonfox'

[editor]
mouse = false
line-number = "relative"
bufferline = "multiple"
color-modes = true
end-of-line-diagnostics = "hint"
scrolloff = 15

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"

[editor.inline-diagnostics]
cursor-line = "warning"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
